from datetime import timedelta
import json , os, sys, shutil, warnings, argparse, uvicorn, logging
from typing import Dict, List
from logging.handlers import RotatingFileHandler
from pathlib import Path
from fastapi.responses import JSONResponse
from fastapi import FastAPI, HTTPException, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles


from src.data_ingestion.pdf_parser import extract_text_from_pdf 
from src.data_ingestion.epub_parser import extract_text_from_epub
from src.data_ingestion.video_parser import extract_text_from_video 
from src.data_ingestion.text_splitter import split_text  
from src.nlp.qa_system import initialize_qa_system, answer_question  
from src.avatar.tts import text_to_speech
from src.avatar.lip_sync import create_talking_avatar
from src.avatar.script_generator import generate_lesson_script
from src.nlp.quiz_system import BasicQuizEngine

from fastapi import FastAPI, Depends, HTTPException
from sqlalchemy.orm import Session
from app import models, schemas, crud, auth
from app.database import SessionLocal, engine

warnings.filterwarnings("ignore")

#Initialize log functions to create system logs whenever APIs are called
LOG_DIR = "logs"
os.makedirs(LOG_DIR, exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        RotatingFileHandler(
            filename=os.path.join(LOG_DIR, 'app.log'),
            maxBytes=1024*1024*5,  # 5MB per log file
            backupCount=5
        ),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger("AI_Professor")

#Initialize backend APIs to connect with frontend calls
AUDIO_DIR = "data/processed/audio"
os.makedirs(AUDIO_DIR, exist_ok=True)
app = FastAPI()
app.mount("/audio", StaticFiles(directory=AUDIO_DIR), name="audio")

#FastAPI middleware handles any request before it is processed by any path or functions
#Our backend API will be running on localhost:5001, our frontend API will be running on localhost:3000
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://localhost:5001"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Users
def get_userdb():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

@app.post("/register", response_model=schemas.UserResponse)
def register_user(user: schemas.UserCreate, db: Session = Depends(get_userdb)):
    db_user = crud.get_user_by_email(db, email=user.email)
    if db_user:
        raise HTTPException(status_code=400, detail="Email already registered")
    return crud.create_user(db=db, user=user)

@app.post("/token")
async def login_for_access_token(email: str, password: str, db: Session = Depends(get_userdb)):
    user = crud.get_user_by_email(db, email)

    if not user or not auth.verify_password(password, user.password):
        raise HTTPException(status_code=400, detail="Incorrect email or password")
    
    access_token_expires = timedelta(minutes=auth.ACCESS_TOKEN_EXPIRE_MINUTES)
    access_token = auth.create_access_token(
        data={"sub": user.email}, expires_delta=access_token_expires
    )

    return {"access_token": access_token, "token_type": "bearer"}
    
    

#Check if our smart AI is initialized. global_db refers to the knowledge graph we generated from materials
@app.get("/health")
async def health_check():
    logger.info("Health check endpoint accessed.")
    return {"status": "ok", "initialized": bool(global_db)}

#This function will handle the question asked by a user in the frontend and send back the answer generated by our model. Check *answer_question* function in src/nlp/qa_system.py for detailed implementation
@app.post("/api/answer")
async def answer_endpoint(question_data: dict):
    try:
        logger.info("Received question: %s", question_data["question"])
        if not global_db:
            raise HTTPException(status_code=503, detail="System not initialized")
            
        response = answer_question(question_data["question"], global_db)
        return {"text": response['text']}
        
    except Exception as e:
        logger.error("Error in /api/answer: %s", str(e))
        return JSONResponse(
            status_code=500,
            content={"error": str(e)}
        )

#This function will take in the answer we generated through last function and send back an audio url for avatar realtime streaming response. Check *text_to_speech* function in src/avatar/tts.py for detailed implementation
@app.post("/api/audio-answer")
async def audio_answer(text_data: dict):
    try:
        logger.info("Generating audio for text: %s", text_data["text"])
        audio_path, audio_url = text_to_speech(text=text_data["text"])
        return {"audio_url": audio_url}
    
    except Exception as e:
        logger.error("Error in /api/audio-answer: %s", str(e))
        return JSONResponse(
            status_code=500,
            content={"error": str(e)}
        )

#This function will take in the files uploaded from frontend and store them inside data/raw folder. Then they will be processed through extract functions for different forms of input. Detailed implementation can be found in src/data_ingestion folder. After they are processed, they will be splitted by split_text function in src/data_ingestion/text_splitter.py and create our knowledge graph by initialize_qa_system function in src/nlp/qa_system.py. Finally, a lesson script of length based on your choice will be generated and stored in data/processed/lesson_script folder in .txt form. Detailed implementation of generate_lesson_script function can be found in src/avatar/script_generator.py.
@app.post("/api/upload")
async def upload_file(files: List[UploadFile] = File(...)):
    try:
        # Create upload directory
        logger.info(f"Uploading {len(files)} file/s!")
        UPLOAD_DIR = "data/raw/"
        os.makedirs(UPLOAD_DIR, exist_ok=True)
        
        text = ""
        # Save file
        for file in files:
            file_path = os.path.join(UPLOAD_DIR, file.filename)
            with open(file_path, "wb") as buffer:
                shutil.copyfileobj(file.file, buffer)
            
            # Process file
            if file.filename.lower().endswith('.pdf'):
                text += extract_text_from_pdf(file_path)
            elif file.filename.lower().endswith('.epub'):
                text += extract_text_from_epub(file_path)
            elif file.filename.lower().split('.')[-1] in ['mp4', 'mov', 'avi']:
                text += extract_text_from_video(file_path)
        
        # Initialize QA system with new content
        global global_db
        chunks = split_text(text)
        global_db = initialize_qa_system(chunks)

        generate_lesson_script(global_db, "TEACHING", 5)
        
        logger.info("File processed successfully: %s", file.filename)
        return {"status": "success", "message": f"Processed {file.filename}"}
    
    except Exception as e:
        logger.error("File processing failed: %s", str(e))
        return JSONResponse(
            status_code=500,
            content={"error": f"File processing failed: {str(e)}"}
        )
    finally:
        if 'file' in locals():
            file.file.close()

#This function will handle "start quiz" button clicked from frontend. It will create a BasicQuizEngine object defined in src/nlp/quiz_system.py. This object has the ability to generate quiz questions and choices based on the number for questions you provided and the lecture script. This function send generated questions back to frontend for users to do.
@app.get("/api/generate-quiz")
async def generate_quiz():
    try:
        logger.info("Generating quiz.")
        global quiz_engine
        quiz_engine = BasicQuizEngine(global_db)
        quiz_engine.generate_quiz_from_script("data/processed/lesson_script/lesson_script.txt", num_questions=3)
        
        # Retrieve all questions
        cursor = quiz_engine.conn.cursor()
        cursor.execute("SELECT * FROM questions ORDER BY RANDOM() LIMIT 10")
        questions = cursor.fetchall()

        return [
            {
                "id": q[0],
                "question": q[1],
                "options": json.loads(q[2]),
                "answer": q[3],
                "concept": q[4]
            } for q in questions
        ]
    except Exception as e:
        logger.info("Quiz generation failed: %s", str(e))
        return JSONResponse(
            status_code=500,
            content={"error": f"Quiz generation failed: {str(e)}"}
        )

#This function utilizes the same BasicQuizEngine object generated from last function. It will clear question database on the backend after the frontend button is clicked.
@app.delete("/api/clear-quiz")
async def clear_quiz():
    try:
        logger.info("Clearing quiz database")
        quiz_engine.clear_all_questions()
        
        return JSONResponse(
            status_code=200,
            content={"message": "Quiz database cleared successfully"}
        )
        
    except Exception as e:
        logger.info("Quiz database clearance failed: %s", str(e))
        return JSONResponse(
            status_code=500,
            content={"error": f"Failed to clear quiz: {str(e)}"}
        )

#This is a backend complete testing function. Nothing will happen at the frontend, we can test our implementations and functions here. All of the output will be shown in your terminal for testing purposes. 
def main():  
    file = Path("data/raw/scrum.epub")
    text = ""
    try:
        #Ingest pdf textbook and build knowledge graph
        print("📖 Loading course material...") 
        if file.suffix.lower() == '.pdf':
            text += extract_text_from_pdf(str(file))
        elif file.suffix.lower() == '.epub':
            text += extract_text_from_epub(str(file))
        elif file.suffix.lower() in ['.mp4', '.mov', '.avi']:
            text += extract_text_from_video(str(file))
        chunks = split_text(text)  
        db = initialize_qa_system(chunks)
        print("✅ Course material loaded successfully!\n")

        #Generate lesson script from knowledge graph
        print("📝 Generating lesson script...")
        generate_lesson_script(db, "TEACHING", 5)
        print("✅ Lecture script prepared successfully!\n")

        #Generate lecture audio from lesson script
        #print("🔊 Rendering lecture audio...")
        #lecture_audio, audio_url = text_to_speech(text=lesson_script)
        #print(f"🔊 Full lecture audio ready: {lecture_audio}")
        #os.system(f'open {lecture_audio}')

        #Generate lecture video from lecture audio
        #print("🎥 Rendering lecture video...")
        #lecture_video = create_talking_avatar(audio_url=audio_url)
        #print(f"🎥 Full lecture video ready: {lecture_video}")
        #os.system(f'open {lecture_video}')  
            
    except Exception as e:
        print(f"❌ Failed to load course material: {str(e)}")
        return

    # Interactive Q&A loop  
    print("👩🏫 AI Professor is ready! Ask a question (type 'exit' to quit):")  
    while True:  
        try:
            question = input("\nYou: ")  
            if question.lower() == "exit":  
                break
                
            print("\n💭 Thinking...", end="\r")
            
            # Get answer with avatar components
            response = answer_question(question, db)
            answer_text = response['text']
            print(f"\n👩🏫 AI Professor: {answer_text}")
            """
            audio_path, audio_url = text_to_speech(text=answer_text)
            print(f"🔊 Audio generated: {audio_path}")
            video_path = create_talking_avatar(audio_url=audio_url)
            print(f"🎥 Video generated: {video_path}")

            os.system(f'open {video_path}')
            """
        except KeyboardInterrupt:
            print("\n👋 Goodbye!")
            break
        except Exception as e:
            print(f"\n⚠️ Error: {str(e)}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--mode', choices=['cli', 'api'], default='api')
    args = parser.parse_args()

    if args.mode == 'cli':
        #If you want to run main() function for backend testing, run this command in your terminal: python main.py --mode=cli
        logger.info("Starting CLI mode.")
        main()
    else:
        #This will start our backend API and connect with frontend functions. Run this command whenever you want to see backend API calls and frontend reactions: python main.py
        logger.info("Starting API server on port 5001.")
        uvicorn.run(app, host="0.0.0.0", port=5001)