import json
import os
import sqlite3
from src.data_ingestion.text_splitter import split_text
from langchain_community.chat_models import ChatOpenAI;
from dotenv import load_dotenv;
import pandas as pd

#Get API key from our .env file for API calls to GPT-4 model
load_dotenv(override=True)
openai_api_key = os.getenv("OPENAI_API_KEY")
if not openai_api_key:
    raise ValueError("OPENAI_API_KEY not found in environment variables")

#This object will be able to generate fundamental factual multiple choice questions based on lesson script
class BasicQuizEngine:
    def __init__(self, db):
        self.knowledge_graph = db #define knowledge graph based on input from object construction
        self.llm = ChatOpenAI(
            model="gpt-4",
            openai_api_key=openai_api_key,
            temperature=0.7
        ) #initialze large learning model for quiz construction, we use GPT-4 here.
        QUIZ_DIR = "data/processed/quiz_data"
        os.makedirs(QUIZ_DIR, exist_ok=True)
        self.conn = sqlite3.connect('data/processed/quiz_data/quiz_data.db') #initialize sqlite3 model for generating and accessing database
        self._init_db()

    #Create a question table to store our questions in the database
    def _init_db(self):
        cursor = self.conn.cursor()
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS questions (
                id INTEGER PRIMARY KEY, 
                question TEXT,
                options TEXT,
                answer INTEGER,
                concept TEXT
            )
        ''')
        self.conn.commit()
    
    #We will split our script into chunks and generate one question for each chunk. After a multiple choice question is generated and 4 options are generated by our llm model, we will store it into the question table in database
    def generate_quiz_from_script(self, script_path: str, num_questions: int):        
        with open(script_path) as f:
            script = f.read()
            
        chunks = split_text(script)
        if len(chunks) < num_questions:
            print(f"There is not enough material to generate {num_questions} questions. Please try again!")
            print(f"The material is only enough to generate {len(chunks)} questions.")
            return
        
        for chunk in chunks[:num_questions]:
            prompt = f"""Generate a multiple choice question from this text:
            {chunk}
            
            Format as JSON:
            {{
                "question": "...",
                "options": ["...", "...", "...", "..."],
                "answer": 0,
                "concept": "..."
            }}"""
            
            response = self.llm.predict(prompt)
            try:
                question = json.loads(response)
                self._store_question(question)
            except:
                continue
    
    #This function will store a question generated into our database "questions" table
    def _store_question(self, question: dict):
        cursor = self.conn.cursor()
        cursor.execute('''
            INSERT INTO questions (question, options, answer, concept)
            VALUES (?, ?, ?, ?)
        ''', (
            question['question'],
            json.dumps(question['options']),
            question['answer'],
            question['concept']
        ))
        self.conn.commit()

    #This function will print all questions from our database "questions" table into terminal
    def print_all_questions(self):
        """Print all questions in a readable format"""
        cursor = self.conn.cursor()
        cursor.execute("SELECT * FROM questions")
        questions = cursor.fetchall()
        
        print("\n" + "="*50)
        print(f"Found {len(questions)} questions in database:")
        print("="*50)
        
        for idx, question in enumerate(questions, 1):
            print(f"\nQuestion #{idx}")
            print(f"ID: {question[0]}")
            print(f"Question: {question[1]}")
            print(f"Options: {json.loads(question[2])}")
            print(f"Correct Answer: {question[3]}")
            print(f"Concept: {question[4]}")
            print("-"*50)
    
    #This function will clear the "questions" table from database and free memeory space for later use
    def clear_all_questions(self):
        """Clear all questions from the database"""
        cursor = self.conn.cursor()
        
        try:
            # Delete all records
            cursor.execute("DELETE FROM questions")
            
            # Only reset sequence if table exists
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='sqlite_sequence'")
            if cursor.fetchone():
                cursor.execute("DELETE FROM sqlite_sequence WHERE name='questions'")
            
            self.conn.commit()
            print("Successfully cleared all quiz questions!")
        
        except sqlite3.Error as e:
            self.conn.rollback()
            raise Exception(f"Database error: {str(e)}")
        
        finally:
            # Optional: Only vacuum if you need to reclaim space
            cursor.execute("VACUUM")
            cursor.close()